name: Build and release
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '21.3.0.java11'

      - name: Install GraalVM's native-image extension
        run: gu install native-image
        
      - name: gradle build
        run: ./gradlew nativeImage

